input_features:
  - name: SEASON_ID
    type: numerical
  - name: Player_ID
    type: numerical
  - name: Game_ID
    type: numerical
  - name: GAME_DATE
    type: date
    preprocessing:
      datetime_format: '%b %d, %Y'
  - name: MATCHUP
    type: category
  - name: MIN
    type: numerical
  - name: FGM
    type: numerical
  - name: FGA
    type: numerical
  - name: FG_PCT
    type: numerical
  - name: FG3M
    type: numerical
  - name: FG3A
    type: numerical
  - name: FG3_PCT
    type: numerical
  - name: FTM
    type: numerical
  - name: FTA
    type: numerical
  - name: FT_PCT
    type: numerical
  - name: OREB
    type: numerical
  - name: DREB
    type: numerical
  - name: REB
    type: numerical
  - name: AST
    type: numerical
  - name: STL
    type: numerical
  - name: BLK
    type: numerical
  - name: TOV
    type: numerical
  - name: PF
    type: numerical
  - name: PTS
    type: numerical
  - name: PLUS_MINUS
    type: numerical

output_features:
  - name: WL
    type: category

training:
  batch_size: 64
  epochs: 50
  learning_rate: 0.001
